name: water
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^22.3.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.8
  flutter_riverpod: ^3.4.3
  flutter_timezone: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.3
  shared_preferences: ^2.5.5
  timezone: ^0.11.1
  water_animation: ^0.0.3

flutter_native_splash:
  color: "#ffffff"

  #background_image:      "assets/background.png"

  image:                assets/splash.png

  fullscreen: true
  
  #! ANDROID 12+ configuration:
  android_12:
    # background color
    color: "#ffffff"

    image:  assets/splash.png  

    #icon_background_color: "#111111"
    # icon_background_color_dark: "#eeeeee" 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  mocktail: ^1.0.5
  rename_app: ^1.6.6

config_name:
  name: "Water Reminder"

flutter:
  uses-material-design: true
